# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1
    working_directory: ~/repo
    steps:
      - checkout # check out the code in the project directory

      - run:
          name: Install dependencies
          command:
            pip install awscli
            bundle install

      - run:
          name: Build Jekyll
          command: rm -rf _site/
          command: bundle exec jekyll build

      - run:
          name: Send files to S3
          command: aws s3 synx _site/ s3://afonso.dev --acl public-read --delete