# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1
    working_directory: ~/repo
    steps:
      - checkout # check out the code in the project directory

      - run:
          name: Install dependencies
          command: bundle install

      - run:
          name: Build Jekyll
          command: |
            rm -rf _site/
            bundle exec jekyll build

      - persist_to_workspace:
        root: /home/built_site
        paths: _site

  deploy:
    docker:
      - image: cibuilds/aws:1.16.1
    steps:
      - attach_workspace:
          at: /home/built_site
      - run:
          name: Send files to S3
          command: aws s3 sync _site/ s3://afonso.dev --acl public-read --delete

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master